souk_categorie:
    resource: "@SoukBundle/Controller/CategorieController.php"
    type:     annotation

souk_article:
    resource: "@SoukBundle/Controller/ArticleController.php"
    type:     annotation

souk:
    resource: "@SoukBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
