services:
#    souk.example:
#        class: SoukBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    demo_user.registration_listener:
        class: SoukBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }